version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql8-data-ocr-P5
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: opencr_pw_root
    ports:
      - "3306:3306"
    volumes:
      - mysql8-data-ocr-P5:/var/lib/mysql
      - ../ressources/sql:/docker-entrypoint-initdb.d

volumes:
  mysql8-data-ocr-P5:
